### ISSUE TITLE
[Enhancement] Gas giant horizon should be down, not to the sides.

### ISSUE THREAD

**Issue by Barerock** [ErzeKawek/EdenRing-1.20PR#29]
Gravitational anomalies be ignored for the moment -- the gas giant planet should be underneath the islands as gravity ultimately centers around it, not underneath it by a few hundred thousand miles. I think there should at least be an option to tune this to a player's liking. I think being able to look down into the blue mass would be cool. Just orbiting a planet as a moon isn't so special, although it does make a nice horizon.

Taking into consideration the gravitational anomalies referenced in the description, I think it's fine to assume it allows the asteroid belt to orient uniformly up/down from the planet's surface. The atmospheric presence isn't really too unrealistic, assuming the planet has a rather dense core and is made of something that allows nitrogen and oxygen to exist in abundance as an outer atmosphere. Our own Earth's atmosphere extends past the moon, just not in any impactful way, so a much larger planet having a much larger and denser atmosphere makes sense, cosmically.

**Comment by ErzeKawek** [comment]
i had a stroke reading this

**Comment by ErzeKawek** [comment]
This is a science fiction mod.

**Comment by Barerock** [comment]
What a rude way to say you're opposed to adding the option to rotate the skybox 90 degrees for some people to have more fun than they otherwise would. Why are you even making mods in public if you're going to be an ass about people _liking them enough to come here to suggest things_. Now this mod isn't interesting because I know its creator is illiterate and rude about it.

**Comment by ErzeKawek** [comment]
@Barerock This is my follow up
> i had a stroke reading this

English is my second language and i had some difficulties reading this Enhancement.

> What a rude way to say you're opposed to adding the option to rotate the skybox 90 degrees for some people to have more fun than they otherwise would.

This is one of the enhancements that i have been opposing since this mod's release, so it's up to you to make a pull request.
(Probably adding this to the "will do when config screen done" Cause currently config screen hasnt been implemented)

> Taking into consideration the gravitational anomalies referenced in the description, I think it's fine to assume it allows the asteroid belt to orient uniformly up/down from the planet's surface.

There are Gravilite Crystals that is sort of influencing the ring asteroids, so that is making the atmosphere act in a weird sort of way.

> Why are you even making mods in public if you're going to be an ass about people liking them enough to come here to suggest things.

I didn't mean to be rude but, The "This is a science fiction mod." which the physics can sort of defy the laws of physics.

> Now this mod isn't interesting because I know its creator is illiterate and rude about it.

I am not being illiterate or rude, i am just having a hard time trying to read and understand what you've just suggested.

**Comment by ErzeKawek** [comment]
and another reason i am opposing this suggestion is i don't have enough time and i have been very busy because of school during June, July, and August (yes the vacation here is very short)
